server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cf?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  application:
    name: admin-service
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka

